Repository kayobruno/minha-quadra, pull requests merged in 2024-07, with the labels that each got.

#12 Add Invoices tables
  app/Enums/InvoiceType.php
  app/Models/Invoice.php
  app/Models/InvoiceItem.php
  app/Traits/Enums.php
  database/factories/InvoiceFactory.php
  database/factories/InvoiceItemFactory.php
  database/migrations/2024_06_27_011949_create_invoice_table.php
  database/migrations/2024_06_27_012339_create_invoice_items_table.php
Labels: enhancement

#13 feat: Add Coverage command
  composer.json
Labels: enhancement

#14 Add PHP Infection
  .gitignore
  composer.json
  composer.lock
  infection.json5
Labels: enhancement

#3 Add new fields to product table
  app/DataTransferObjects/ProductData.php
  app/Http/Requests/Dash/Product/CreateRequest.php
  app/Models/Product.php
  database/migrations/2024_06_26_235226_add_ean_and_manage_stock_fields_to_product_table.php
  resources/views/content/products/_partials/form.blade.php
  resources/views/content/products/index.blade.php
  tests/Feature/Api/BookingControllerTest.php
  tests/Feature/Dash/Product/CreateProductTest.php
  tests/Feature/Dash/Product/UpdateProductTest.php
  tests/Feature/Model/ProductTest.php
Labels: enhancement

#23 Add unique validation to ean product field
  app/Http/Requests/Dash/Product/CreateRequest.php
  app/Http/Requests/Dash/Product/UpdateRequest.php
  tests/Feature/Dash/Product/UpdateProductTest.php
Labels: bug

#25 fix: Add unique validation to document field on Supplier form
  app/Http/Requests/Dash/Supplier/CreateRequest.php
  app/Http/Requests/Dash/Supplier/UpdateRequest.php
  lang/pt_BR/validation.php
  tests/Feature/Dash/Supplier/UpdateSupplierTest.php
Labels: bug

#26 fix: Save unused fields on Supplier create form
  app/DataTransferObjects/SupplierData.php
  tests/Feature/Dash/Supplier/CreateSupplierTest.php
Labels: bug

#27 fix: Remove fields that should be calculated and not just saved
  app/Models/Order.php
  database/factories/OrderFactory.php
  database/migrations/2024_02_25_213819_create_orders_table.php
  resources/views/content/orders/index.blade.php
  tests/Feature/Dash/Order/ListOrdersTest.php
  tests/Feature/Model/OrderTest.php
Labels: invalid

#32 feat: Add note field to orders
  app/Models/Order.php
  database/factories/OrderFactory.php
  database/migrations/2024_07_13_001849_add_note_field_to_orders_table.php
  tests/Feature/Model/OrderTest.php
Labels: enhancement

#33 feat: Add OrderDataParam
  app/DataTransferObjects/OrderDataParam.php
  app/Models/User.php
Labels: enhancement

#34 refactor: Order Repository
  app/Contracts/OrderRepository.php
  app/Repositories/OrderEloquentRepository.php
  tests/Unit/Repositories/OrderEloquentRepositoryTest.php
Labels: enhancement

#35 test: Add more tests to MerchantEloquentRepository
  app/Repositories/MerchantEloquentRepository.php
  tests/Unit/Repositories/MerchantEloquentRepositoryTest.php
Labels: enhancement

#31 feat: Introduce Create Order
  resources/views/content/orders/create.blade.php
  tests/Feature/Dash/Order/CreateOrderTest.php
Labels: enhancement

#30 feat: create new form to save invoices
  app/Enums/InvoiceType.php
  app/Http/Controllers/Dash/InvoiceController.php
  resources/menu/verticalMenu.json
  resources/views/content/invoices/_partials/form.blade.php
  resources/views/content/invoices/create.blade.php
  resources/views/content/invoices/index.blade.php
  routes/web.php
  tests/Feature/Dash/Invoice/CreateInvoiceTest.php
  tests/Feature/Dash/Invoice/ListInvoiceTest.php
Labels: enhancement

#36 refact: ProductRepository
  app/Repositories/ProductEloquentRepository.php
  tests/Unit/Repositories/ProductEloquentRepositoryTest.php
Labels: enhancement

#37 refact: CustomerRepository
  app/Repositories/CustomerEloquentRepository.php
  tests/Unit/Repositories/CustomerEloquentRepositoryTest.php
Labels: enhancement

#38 refact: CourtRepository
  app/Repositories/CourtEloquentRepository.php
  tests/Unit/Repositories/CourtEloquentRepositoryTest.php
Labels: enhancement

#39 refact: SupplierRepository
  app/Repositories/SupplierEloquentRepository.php
  tests/Unit/Repositories/SupplierEloquentRepositoryTest.php
Labels: enhancement

#45 fix: Intermittent Test about Create Booking with date in the future
  tests/Feature/Api/BookingControllerTest.php
Labels: bug

#44 test: Add more tests to Customer
  tests/Feature/Dash/Customer/CreateCustomerTest.php
  tests/Feature/Dash/Customer/RemoveCustomerTest.php
  tests/Feature/Dash/Customer/UpdateCustomerTest.php
Labels: enhancement

#46 chore: Edit minimum coverage to 92%
  .github/workflows/app.yaml
Labels: enhancement

#40 feat: add invoice request
  app/Http/Requests/Dash/Invoice/CreateRequest.php
Labels: enhancement
